---
title: Performa Diagnostik Biomarker Karsinoma Hepatoselular
authors:
  - name: dr. Kadek Adit Wiryadana
    affiliation: Universitas Udayana
    roles: writing
    corresponding: true
  - name: dr. Gde Somayana, SpPD, K-GEH
    affiliation: Universitas Udayana
    roles: writing
    corresponding: true
bibliography: references.bib
csl: wiryadana.csl
tbl-cap-location: top
output-dir: docs
---

```{r echo=F}
#| label: libraray
#| message: false
#| warning: false

library("tidyverse")
library("googlesheets4")
library("gt")
library("gtExtras")
```

------------------------------------------------------------------------

## Lengkap

```{r}
#| label: tbl-lengkap
#| message: false
#| warning: false
#| echo: false
#| tbl-cap: Data performa diagnostik beberapa biomarker Karsinoma Hepatoselular.

lengkap <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1HpX1F35g2x28XQNtHGjz6gg3EIO0vZpevJLsJWswoVA/edit?gid=151019815#gid=151019815", sheet = "lengkap")

lengkap_tipis <- lengkap %>% select(No.total, Biomarker, Author, Year, Region, 'Case-control', Sensitivity, Specificity)

dt_lengkap <- lengkap_tipis %>% 
  dplyr::mutate(
    Sensitivitas = Sensitivity * 100,
    Spesifisitas = Specificity * 100
  ) %>%
  gt() %>% 
  gt_plt_bar_pct(
    Sensitivitas,
    labels = TRUE,
    scaled = TRUE
  ) %>%
  gt_plt_bar_pct(
    Spesifisitas,
    labels = TRUE,
    fill = "forestgreen",
    scaled = TRUE
  ) %>%
  cols_label(
    Author = "Peneliti",
    Year = "Tahun",
    Region = "Negara",
    "Case-control" = "Kasus-Kontrol"
  ) %>%
  cols_hide(columns = c(Sensitivity, Specificity)) %>%
  opt_table_font(
    font = "times new roman",
    size = 12,
    color = "black"
  ) %>%
  tab_style(
    style = cell_text(
      size = 14,
      weight = "bold"
    ),
    locations = cells_column_labels()
  ) %>%
  fmt_number(
    dec_mark = ","
  )

dt_lengkap %>%
  gtsave(filename = "PNG/lengkap.png")
```

## AFP


```{r}
#| label: tbl-afp
#| message: false
#| warning: false
#| echo: false
#| tbl-cap: "Data performa diagnostik Alfa-Feto Protein sebagai marker Karsinoma Hepatoselular."


AFP <- lengkap %>% 
      select(No, Biomarker, Author, Year, Region, 'Case-control', Sensitivity, Specificity) %>%
      filter(Biomarker == "AFP")

dt_AFP <- AFP %>% 
  dplyr::mutate(
    Sensitivitas = Sensitivity * 100,
    Spesifisitas = Specificity * 100
  ) %>%
  gt() %>% 
  gt_plt_bar_pct(
    Sensitivitas,
    labels = TRUE,
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  gt_plt_bar_pct(
    Spesifisitas,
    labels = TRUE,
    fill = "forestgreen",
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  cols_label(
    Author = "Peneliti",
    Year = "Tahun",
    Region = "Negara",
    "Case-control" = "Kasus-Kontrol"
  ) %>%
  cols_hide(columns = c(Biomarker,Sensitivity, Specificity)) %>%
  opt_table_font(
    font = "times new roman",
    size = 12,
    color = "black"
  ) %>%
  tab_style(
    style = cell_text(
      size = 14,
      weight = "bold"
    ),
    locations = cells_column_labels()
  )

dt_AFP %>%
  gtsave(filename = "PNG/afp.png")
```

## AFP dan AFP-L3


```{r}
#| label: tbl-afp_afpl3
#| message: false
#| warning: false
#| echo: false
#| tbl-cap: "Data performa diagnostik Alfa-Feto Protein serta fraksi L-3 sebagai marker Karsinoma Hepatoselular."


AFP_AFPL3 <- lengkap %>% 
      select(No, Biomarker, Author, Year, Region, 'Case-control', Sensitivity, Specificity) %>%
      filter(Biomarker == "AFP+AFP-L3")

dt_AFP_AFPL3 <- AFP_AFPL3 %>% 
  dplyr::mutate(
    Sensitivitas = Sensitivity * 100,
    Spesifisitas = Specificity * 100
  ) %>%
  gt() %>% 
  gt_plt_bar_pct(
    Sensitivitas,
    labels = TRUE,
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  gt_plt_bar_pct(
    Spesifisitas,
    labels = TRUE,
    fill = "forestgreen",
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  cols_label(
    Author = "Peneliti",
    Year = "Tahun",
    Region = "Negara",
    "Case-control" = "Kasus-Kontrol"
  ) %>%
  cols_hide(columns = c(Biomarker,Sensitivity, Specificity)) %>%
  opt_table_font(
    font = "times new roman",
    size = 12,
    color = "black"
  ) %>%
  tab_style(
    style = cell_text(
      size = 14,
      weight = "bold"
    ),
    locations = cells_column_labels()
  ) 

dt_AFP_AFPL3 %>%
  gtsave(filename = "PNG/afp_afpl3.png")
```

## AFP dengan kombinasi AFP-L3 dan DCP


```{r}
#| label: tbl-afp-afpl3-dcp
#| message: false
#| warning: false
#| echo: false
#| tbl-cap: "Data performa diagnostik Alfa-Feto Protein kombinasi dengan Alfa-Feto Protein L-3 dan DCP sebagai marker Karsinoma Hepatoselular."


AFP_L3_DCP <- lengkap %>% 
      select(No, Biomarker, Author, Year, Region, 'Case-control', Sensitivity, Specificity) %>%
      filter(Biomarker == "AFP+AFP-L3+DCP")

dt_AFP_L3_DCP <- AFP_L3_DCP %>% 
  dplyr::mutate(
    Sensitivitas = Sensitivity * 100,
    Spesifisitas = Specificity * 100
  ) %>%
  gt() %>% 
  gt_plt_bar_pct(
    Sensitivitas,
    labels = TRUE,
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  gt_plt_bar_pct(
    Spesifisitas,
    labels = TRUE,
    fill = "forestgreen",
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  cols_label(
    Author = "Peneliti",
    Year = "Tahun",
    Region = "Negara",
    "Case-control" = "Kasus-Kontrol"
  ) %>%
  cols_hide(columns = c(Biomarker,Sensitivity, Specificity)) %>%
  opt_table_font(
    font = "times new roman",
    size = 12,
    color = "black"
  ) %>%
  tab_style(
    style = cell_text(
      size = 14,
      weight = "bold"
    ),
    locations = cells_column_labels()
  )

dt_AFP_L3_DCP %>%
  gtsave(filename = "PNG/afp_l3_dcp.png")
```

## AFP dengan kombinasi AFP-L3 dan DCP


```{r}
#| label: tbl-afp-dcp
#| message: false
#| warning: false
#| echo: false
#| tbl-cap: "Data performa diagnostik Alfa-Feto Protein kombinasi DCP sebagai marker Karsinoma Hepatoselular."


AFP_DCP <- lengkap %>% 
      select(No, Biomarker, Author, Year, Region, 'Case-control', Sensitivity, Specificity) %>%
      filter(Biomarker == "AFP+DCP" | Biomarker == "AFP/DCP")

dt_AFP_DCP <- AFP_DCP %>% 
  dplyr::mutate(
    Sensitivitas = Sensitivity * 100,
    Spesifisitas = Specificity * 100
  ) %>%
  gt() %>% 
  gt_plt_bar_pct(
    Sensitivitas,
    labels = TRUE,
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  gt_plt_bar_pct(
    Spesifisitas,
    labels = TRUE,
    fill = "forestgreen",
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  cols_label(
    Author = "Peneliti",
    Year = "Tahun",
    Region = "Negara",
    "Case-control" = "Kasus-Kontrol"
  ) %>%
  cols_hide(columns = c(Sensitivity, Specificity)) %>%
  opt_table_font(
    font = "times new roman",
    size = 12,
    color = "black"
  ) %>%
  tab_style(
    style = cell_text(
      size = 14,
      weight = "bold"
    ),
    locations = cells_column_labels()
  )

dt_AFP_DCP %>%
  gtsave(filename = "PNG/afp_dcp.png")
```

## AFP dengan kombinasi AFP-L3 dan GCP3


```{r}
#| label: tbl-afp-gpc3
#| message: false
#| warning: false
#| echo: false
#| tbl-cap: "Data performa diagnostik Alfa-Feto Protein kombinasi GCP3 sebagai marker Karsinoma Hepatoselular."


AFP_GPC3 <- lengkap %>% 
      select(No, Biomarker, Author, Year, Region, 'Case-control', Sensitivity, Specificity) %>%
      filter(Biomarker == "AFP+GPC3")

dt_AFP_GPC3 <- AFP_GPC3 %>% 
  dplyr::mutate(
    Sensitivitas = Sensitivity * 100,
    Spesifisitas = Specificity * 100
  ) %>%
  gt() %>% 
  gt_plt_bar_pct(
    Sensitivitas,
    labels = TRUE,
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  gt_plt_bar_pct(
    Spesifisitas,
    labels = TRUE,
    fill = "forestgreen",
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  cols_label(
    Author = "Peneliti",
    Year = "Tahun",
    Region = "Negara",
    "Case-control" = "Kasus-Kontrol"
  ) %>%
  cols_hide(columns = c(Biomarker, Sensitivity, Specificity)) %>%
  opt_table_font(
    font = "times new roman",
    size = 12,
    color = "black"
  ) %>%
  tab_style(
    style = cell_text(
      size = 14,
      weight = "bold"
    ),
    locations = cells_column_labels()
  )

dt_AFP_GPC3 %>%
  gtsave(filename = "PNG/afp_gpc3.png")
```

## DCP atau PIVKA-II


```{r}
#| label: tbl-dcp
#| message: false
#| warning: false
#| echo: false
#| tbl-cap: "Data performa diagnostik DCP sebagai marker Karsinoma Hepatoselular."


DCP <- lengkap %>% 
      select(No, Biomarker, Author, Year, Region, 'Case-control', Sensitivity, Specificity) %>%
      filter(Biomarker == "DCP")

dt_DCP <- DCP %>% 
  dplyr::mutate(
    Sensitivitas = Sensitivity * 100,
    Spesifisitas = Specificity * 100
  ) %>%
  gt() %>% 
  gt_plt_bar_pct(
    Sensitivitas,
    labels = TRUE,
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  gt_plt_bar_pct(
    Spesifisitas,
    labels = TRUE,
    fill = "forestgreen",
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  cols_label(
    Author = "Peneliti",
    Year = "Tahun",
    Region = "Negara",
    "Case-control" = "Kasus-Kontrol"
  ) %>%
  cols_hide(columns = c(Sensitivity, Specificity)) %>%
  opt_table_font(
    font = "times new roman",
    size = 12,
    color = "black"
  ) %>%
  tab_style(
    style = cell_text(
      size = 14,
      weight = "bold"
    ),
    locations = cells_column_labels()
  )

dt_DCP %>%
  gtsave(filename = "PNG/dcp.png")
```

## GPC-3

```{r}
#| label: tbl-gpc3
#| message: false
#| warning: false
#| echo: false
#| tbl-cap: "Data performa diagnostik Golgi Protein-3 sebagai marker Karsinoma Hepatoselular."


GPC3 <- lengkap %>% 
      select(No, Biomarker, Author, Year, Region, 'Case-control', Sensitivity, Specificity) %>%
      filter(Biomarker == "GPC3")

dt_GPC3 <- GPC3 %>% 
  dplyr::mutate(
    Sensitivitas = Sensitivity * 100,
    Spesifisitas = Specificity * 100
  ) %>%
  gt() %>% 
  gt_plt_bar_pct(
    Sensitivitas,
    labels = TRUE,
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  gt_plt_bar_pct(
    Spesifisitas,
    labels = TRUE,
    fill = "forestgreen",
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  cols_label(
    Author = "Peneliti",
    Year = "Tahun",
    Region = "Negara",
    "Case-control" = "Kasus-Kontrol"
  ) %>%
  cols_hide(columns = c(Sensitivity, Specificity)) %>%
  opt_table_font(
    font = "times new roman",
    size = 12,
    color = "black"
  ) %>%
  tab_style(
    style = cell_text(
      size = 14,
      weight = "bold"
    ),
    locations = cells_column_labels()
  )

dt_GPC3 %>%
  gtsave(filename = "PNG/gpc3.png")
```

## DKK-1

```{r}
#| label: tbl-dkk1
#| message: false
#| warning: false
#| echo: false
#| tbl-cap: "Data performa diagnostik DKK-1 sebagai marker Karsinoma Hepatoselular."


DKK1 <- lengkap %>% 
      select(No, Biomarker, Author, Year, Region, 'Case-control', Sensitivity, Specificity) %>%
      filter(Biomarker == "DKK1")

dt_DKK1 <- DKK1 %>% 
  dplyr::mutate(
    Sensitivitas = Sensitivity * 100,
    Spesifisitas = Specificity * 100
  ) %>%
  gt() %>% 
  gt_plt_bar_pct(
    Sensitivitas,
    labels = TRUE,
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  gt_plt_bar_pct(
    Spesifisitas,
    labels = TRUE,
    fill = "forestgreen",
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  cols_label(
    Author = "Peneliti",
    Year = "Tahun",
    Region = "Negara",
    "Case-control" = "Kasus-Kontrol"
  ) %>%
  cols_hide(columns = c(Sensitivity, Specificity)) %>%
  opt_table_font(
    font = "times new roman",
    size = 12,
    color = "black"
  ) %>%
  tab_style(
    style = cell_text(
      size = 14,
      weight = "bold"
    ),
    locations = cells_column_labels()
  )

dt_DKK1 %>%
  gtsave(filename = "PNG/dkk1.png")
```

## AFP-L3

```{r}
#| label: tbl-afpl3
#| message: false
#| warning: false
#| echo: false
#| tbl-cap: "Data performa diagnostik AFP-L3 sebagai marker Karsinoma Hepatoselular."


AFPL3 <- lengkap %>% 
      select(No, Biomarker, Author, Year, Region, 'Case-control', Sensitivity, Specificity) %>%
      filter(Biomarker == "AFP-L3")

dt_AFPL3 <- AFPL3 %>% 
  dplyr::mutate(
    Sensitivitas = Sensitivity * 100,
    Spesifisitas = Specificity * 100
  ) %>%
  gt() %>% 
  gt_plt_bar_pct(
    Sensitivitas,
    labels = TRUE,
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  gt_plt_bar_pct(
    Spesifisitas,
    labels = TRUE,
    fill = "forestgreen",
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  cols_label(
    Author = "Peneliti",
    Year = "Tahun",
    Region = "Negara",
    "Case-control" = "Kasus-Kontrol"
  ) %>%
  cols_hide(columns = c(Sensitivity, Specificity)) %>%
  opt_table_font(
    font = "times new roman",
    size = 12,
    color = "black"
  ) %>%
  tab_style(
    style = cell_text(
      size = 14,
      weight = "bold"
    ),
    locations = cells_column_labels()
  )

dt_AFPL3 %>%
  gtsave(filename = "PNG/afp-l3.png")
```

## AFU

```{r}
#| label: tbl-afu
#| message: false
#| warning: false
#| echo: false
#| tbl-cap: "Data performa diagnostik AFU sebagai marker Karsinoma Hepatoselular."


AFU <- lengkap %>% 
      select(No, Biomarker, Author, Year, Region, 'Case-control', Sensitivity, Specificity) %>%
      filter(Biomarker == "AFU")

dt_AFU <- AFU %>% 
  dplyr::mutate(
    Sensitivitas = Sensitivity * 100,
    Spesifisitas = Specificity * 100
  ) %>%
  gt() %>% 
  gt_plt_bar_pct(
    Sensitivitas,
    labels = TRUE,
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  gt_plt_bar_pct(
    Spesifisitas,
    labels = TRUE,
    fill = "forestgreen",
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  cols_label(
    Author = "Peneliti",
    Year = "Tahun",
    Region = "Negara",
    "Case-control" = "Kasus-Kontrol"
  ) %>%
  cols_hide(columns = c(Sensitivity, Specificity)) %>%
  opt_table_font(
    font = "times new roman",
    size = 12,
    color = "black"
  ) %>%
  tab_style(
    style = cell_text(
      size = 14,
      weight = "bold"
    ),
    locations = cells_column_labels()
  )

dt_AFU %>%
  gtsave(filename = "PNG/afu.png")
```

## CA199

```{r}
#| label: tbl-ca199
#| message: false
#| warning: false
#| echo: false
#| tbl-cap: "Data performa diagnostik CA199 sebagai marker Karsinoma Hepatoselular."


CA199 <- lengkap %>% 
      select(No, Biomarker, Author, Year, Region, 'Case-control', Sensitivity, Specificity) %>%
      filter(Biomarker == "CA199")

dt_CA199 <- CA199 %>% 
  dplyr::mutate(
    Sensitivitas = Sensitivity * 100,
    Spesifisitas = Specificity * 100
  ) %>%
  gt() %>% 
  gt_plt_bar_pct(
    Sensitivitas,
    labels = TRUE,
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  gt_plt_bar_pct(
    Spesifisitas,
    labels = TRUE,
    fill = "forestgreen",
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  cols_label(
    Author = "Peneliti",
    Year = "Tahun",
    Region = "Negara",
    "Case-control" = "Kasus-Kontrol"
  ) %>%
  cols_hide(columns = c(Sensitivity, Specificity)) %>%
  opt_table_font(
    font = "times new roman",
    size = 12,
    color = "black"
  ) %>%
  tab_style(
    style = cell_text(
      size = 14,
      weight = "bold"
    ),
    locations = cells_column_labels()
  )

dt_CA199 %>%
  gtsave(filename = "PNG/ca199.png")
```


## HSP-90 Alpha

```{r}
#| label: tbl-hsp90alpha
#| message: false
#| warning: false
#| echo: false
#| tbl-cap: "Data performa diagnostik HSP-90 Alpha sebagai marker Karsinoma Hepatoselular."


hsp90alpha <- lengkap %>% 
      select(No, Biomarker, Author, Year, Region, 'Case-control', Sensitivity, Specificity) %>%
      filter(Biomarker == "Hsp90alpha")

dt_hsp90alpha <- hsp90alpha %>% 
  dplyr::mutate(
    Sensitivitas = Sensitivity * 100,
    Spesifisitas = Specificity * 100
  ) %>%
  gt() %>% 
  gt_plt_bar_pct(
    Sensitivitas,
    labels = TRUE,
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  gt_plt_bar_pct(
    Spesifisitas,
    labels = TRUE,
    fill = "forestgreen",
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  cols_label(
    Author = "Peneliti",
    Year = "Tahun",
    Region = "Negara",
    "Case-control" = "Kasus-Kontrol"
  ) %>%
  cols_hide(columns = c(Sensitivity, Specificity)) %>%
  opt_table_font(
    font = "times new roman",
    size = 12,
    color = "black"
  ) %>%
  tab_style(
    style = cell_text(
      size = 14,
      weight = "bold"
    ),
    locations = cells_column_labels()
  )

dt_hsp90alpha %>%
  gtsave(filename = "PNG/hsp90alpha.png")
```

## Midkine

```{r}
#| label: tbl-midkine
#| message: false
#| warning: false
#| echo: false
#| tbl-cap: "Data performa diagnostik Midkine sebagai marker Karsinoma Hepatoselular."


Midkine <- lengkap %>% 
      select(No, Biomarker, Author, Year, Region, 'Case-control', Sensitivity, Specificity) %>%
      filter(Biomarker == "Midkine")

dt_Midkine <- Midkine %>% 
  dplyr::mutate(
    Sensitivitas = Sensitivity * 100,
    Spesifisitas = Specificity * 100
  ) %>%
  gt() %>% 
  gt_plt_bar_pct(
    Sensitivitas,
    labels = TRUE,
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  gt_plt_bar_pct(
    Spesifisitas,
    labels = TRUE,
    fill = "forestgreen",
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  cols_label(
    Author = "Peneliti",
    Year = "Tahun",
    Region = "Negara",
    "Case-control" = "Kasus-Kontrol"
  ) %>%
  cols_hide(columns = c(Sensitivity, Specificity)) %>%
  opt_table_font(
    font = "times new roman",
    size = 12,
    color = "black"
  ) %>%
  tab_style(
    style = cell_text(
      size = 14,
      weight = "bold"
    ),
    locations = cells_column_labels()
  )

dt_Midkine %>%
  gtsave(filename = "PNG/midkine.png")
```

## OPN

```{r}
#| label: tbl-opn
#| message: false
#| warning: false
#| echo: false
#| tbl-cap: "Data performa diagnostik OPN sebagai marker Karsinoma Hepatoselular."


OPN <- lengkap %>% 
      select(No, Biomarker, Author, Year, Region, 'Case-control', Sensitivity, Specificity) %>%
      filter(Biomarker == "OPN")

dt_OPN<- OPN %>% 
  dplyr::mutate(
    Sensitivitas = Sensitivity * 100,
    Spesifisitas = Specificity * 100
  ) %>%
  gt() %>% 
  gt_plt_bar_pct(
    Sensitivitas,
    labels = TRUE,
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  gt_plt_bar_pct(
    Spesifisitas,
    labels = TRUE,
    fill = "forestgreen",
    scaled = TRUE,
    font_size = '12px'
  ) %>%
  cols_label(
    Author = "Peneliti",
    Year = "Tahun",
    Region = "Negara",
    "Case-control" = "Kasus-Kontrol"
  ) %>%
  cols_hide(columns = c(Sensitivity, Specificity)) %>%
  opt_table_font(
    font = "times new roman",
    size = 12,
    color = "black"
  ) %>%
  tab_style(
    style = cell_text(
      size = 14,
      weight = "bold"
    ),
    locations = cells_column_labels()
  )

dt_OPN %>%
  gtsave(filename = "PNG/opn.png")
```









































































































































